[tool.yapf]
ALIGN_CLOSING_BRACKET_WITH_VISUAL_INDENT=false
ALLOW_MULTILINE_LAMBDAS=false
ALLOW_MULTILINE_DICTIONARY_KEYS=false
ALLOW_SPLIT_BEFORE_DEFAULT_OR_NAMED_ASSIGNS=true
ALLOW_SPLIT_BEFORE_DICT_VALUE=true
ARITHMETIC_PRECEDENCE_INDICATION=false
BLANK_LINE_BEFORE_CLASS_DOCSTRING=false
BLANK_LINE_BEFORE_MODULE_DOCSTRING=false
BLANK_LINE_BEFORE_NESTED_CLASS_OR_DEF=false
BLANK_LINES_AROUND_TOP_LEVEL_DEFINITION=2
BLANK_LINES_BETWEEN_TOP_LEVEL_IMPORTS_AND_VARIABLES=1
COALESCE_BRACKETS=true
COLUMN_LIMIT=100
CONTINUATION_ALIGN_STYLE="SPACE"
CONTINUATION_INDENT_WIDTH=4
DEDENT_CLOSING_BRACKETS=true
DISABLE_ENDING_COMMA_HEURISTIC=false
EACH_DICT_ENTRY_ON_SEPARATE_LINE=true
FORCE_MULTILINE_DICT=false
I18N_COMMENT=""
I18N_FUNCTION_CALL=""
INDENT_CLOSING_BRACKETS=false
INDENT_DICTIONARY_VALUE=true
INDENT_WIDTH=4
INDENT_BLANK_LINES=false
JOIN_MULTIPLE_LINES=false
NO_SPACES_AROUND_SELECTED_BINARY_OPERATORS={}
SPACE_BETWEEN_ENDING_COMMA_AND_CLOSING_BRACKET=true
SPACE_INSIDE_BRACKETS=false
SPACES_AROUND_POWER_OPERATOR=false
SPACES_AROUND_DEFAULT_OR_NAMED_ASSIGN=false
SPACES_AROUND_DICT_DELIMITERS=false
SPACES_AROUND_LIST_DELIMITERS=false
SPACES_AROUND_SUBSCRIPT_COLON=false
SPACES_AROUND_TUPLE_DELIMITERS=false
SPACES_BEFORE_COMMENT=2
SPLIT_ARGUMENTS_WHEN_COMMA_TERMINATED=false
SPLIT_ALL_COMMA_SEPARATED_VALUES=false
SPLIT_ALL_TOP_LEVEL_COMMA_SEPARATED_VALUES=false
SPLIT_BEFORE_ARITHMETIC_OPERATOR=true
SPLIT_BEFORE_BITWISE_OPERATOR=false
SPLIT_BEFORE_CLOSING_BRACKET=true
SPLIT_BEFORE_DICT_SET_GENERATOR=true
SPLIT_BEFORE_DOT=false
SPLIT_BEFORE_FIRST_ARGUMENT=false
SPLIT_BEFORE_EXPRESSION_AFTER_OPENING_PAREN=true
SPLIT_BEFORE_LOGICAL_OPERATOR=true
SPLIT_BEFORE_NAMED_ASSIGNS=true
SPLIT_COMPLEX_COMPREHENSION=false
SPLIT_PENALTY_AFTER_OPENING_BRACKET=0
SPLIT_PENALTY_AFTER_UNARY_OPERATOR=10000
SPLIT_PENALTY_ARITHMETIC_OPERATOR=300
SPLIT_PENALTY_BEFORE_IF_EXPR=30
SPLIT_PENALTY_BITWISE_OPERATOR=300
SPLIT_PENALTY_COMPREHENSION=80
SPLIT_PENALTY_EXCESS_CHARACTER=7000
SPLIT_PENALTY_FOR_ADDED_LINE_SPLIT=30
SPLIT_PENALTY_IMPORT_NAMES=0
SPLIT_PENALTY_LOGICAL_OPERATOR=300
USE_TABS=false
